apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisclient-deployment
  labels:
    app: swg-redis-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swg-redis-client
  template:
    metadata:
      labels:
        app: swg-redis-client
    spec:
      containers:
        - name: swg-redis-client
          image: cdugga/scaling-with-go-redisclient:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 81