apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisclient-deployment
  labels:
    app: redisclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redisclient
      tier: backend
  template:
    metadata:
      labels:
        app: redisclient
        tier: backend
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        searches:
          - default.svc.cluster.local
      containers:
        - name: swg-redis-client
          image: cdugga/scaling-with-go-redisclient:1.0.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: redis-client-svc
spec:
  selector:
    app: redisclient
    tier: backend
  ports:
    - port: 8081
      targetPort: 8081
