apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: swg-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swg-server
  template:
    metadata:
      labels:
        app: swg-server
    spec:
      containers:
        - name: swg-server
          image: cdugga/scaling-with-go-server:1.0.0
          ports:
            - containerPort: 80